In [2]:
import pandas as pd
# 读取Excel文件
df = pd.read_excel('学生成绩数据.xlsx')#, usecols = ['姓名','语文','数学','英语','物理','化学','生物'])
#数据处理
df['总成绩'] = df['语文'] + df['数学'] + df['英语'] + df['物理'] + df['化学'] + df['生物']
#写入数据
df.to_excel('学生成绩数据_01.xlsx', index=False)
#检查
print(df['总成绩'].max())#最高分
print(df['总成绩'].min())#最低分
print(df['总成绩'].mean())#平均分

715.0
288.0
515.2662662662663

In [3]:

#数据查看—————— head tail describe info shape columns
print(df.head(10))#显示前10行数据
print(df.tail(10))#显示后10行数据
# print(df.describe())#数据统计描述  std-标准差
print(df.info())#数据信息
print(df.shape)#数据行列(1000, 11)  行列数
print(df.columns)#数据列名 #Index(['学号', '姓名', '语文', '数学', '英语', '物理', '化学', '生物', '体育', '美术', '音乐'], dtype='str')

         学号   姓名     语文   数学   英语   物理   化学   生物 体育 美术   音乐    总成绩
0  20260001  王娟杰  125.0  103  131  100   61  -61  A  D    C  459.0
1  20260002  宋强玲    NaN   90   88   40    0   97  B  C    A    NaN
2  20260003  朱芳伟   76.0   59  150   61   70   25  C  A    C  441.0
3  20260004  赵军鑫   87.0  141  118   49   37   63  B  A    D  495.0
4  20260005  黄玲勇  137.0   65  115    9   28   74  D  C  NaN  428.0
5  20260006  高娟伟  116.0  139   73   21   91   52  B  B    C  492.0
6  20260007  杨勇明  119.0   95   84   86   99   96  C  A    B  579.0
7  20260008  黄明强   55.0  146  102   56  100   41  C  D    B  500.0
8  20260009  刘秀秀  121.0   85  121  100   67  100  C  B    A  594.0
9  20260010  许芳丽   58.0  144  140   69   52   23  C  B    A  486.0
           学号   姓名     语文   数学   英语   物理  化学   生物 体育 美术 音乐    总成绩
990  20260991  杨芳强  138.0  135  101   93  43   53  B  B  C  563.0
991  20260992  黄勇玲  150.0  126   74   69  55   92  D  A  D  566.0
992  20260993  宋玲娟  102.0   99  110   64  62  100  D  C  C  537.0
993  20260994  周杰强   91.0  136  133   60  58  100  D  B  C  578.0
994  20260995  高玲艳   38.0  120   95   77  86  100  B  B  D  516.0
995  20260996  孙伟勇  123.0  150   80   74  26   64  B  C  D  517.0
996  20260997  邓鑫艳   62.0   93  139   79  85   79  C  C  A  537.0
997  20260998  王静敏   67.0   52  135   69  54   36  B  C  D  413.0
998  20260999  张艳强  112.0  119  111  100  72   24  C  C  B  538.0
999  20261000  马艳艳   58.0   60  106   85  92   93  B  C  D  494.0
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   学号      1000 non-null   int64
 1   姓名      1000 non-null   str
 2   语文      999 non-null    float64
 3   数学      1000 non-null   int64
 4   英语      1000 non-null   int64
 5   物理      1000 non-null   int64
 6   化学      1000 non-null   int64
 7   生物      1000 non-null   int64
 8   体育      1000 non-null   str
 9   美术      1000 non-null   str
 10  音乐      999 non-null    str
 11  总成绩     999 non-null    float64
dtypes: float64(2), int64(6), str(4)
memory usage: 105.6 KB
None
(1000, 12)
Index(['学号', '姓名', '语文', '数学', '英语', '物理', '化学', '生物', '体育', '美术', '音乐',
       '总成绩'],
      dtype='str')

In [4]:
#选择数据————
#选择列
#单列
print(df['姓名'])#单列数据
#多列
print(df[['姓名', '语文', '数学']])#多列数据
#选择行————iloc loc[start:stop:step]
print(df.iloc[0:10])#显示前10行数据 基于行号选择 左闭右开
print(df.loc[0:10])#显示前10行数据 基于索引选择 全闭

0      王娟杰
1      宋强玲
2      朱芳伟
3      赵军鑫
4      黄玲勇
      ...
995    孙伟勇
996    邓鑫艳
997    王静敏
998    张艳强
999    马艳艳
Name: 姓名, Length: 1000, dtype: str
      姓名     语文   数学
0    王娟杰  125.0  103
1    宋强玲    NaN   90
2    朱芳伟   76.0   59
3    赵军鑫   87.0  141
4    黄玲勇  137.0   65
..   ...    ...  ...
995  孙伟勇  123.0  150
996  邓鑫艳   62.0   93
997  王静敏   67.0   52
998  张艳强  112.0  119
999  马艳艳   58.0   60

[1000 rows x 3 columns]
         学号   姓名     语文   数学   英语   物理   化学   生物 体育 美术   音乐    总成绩
0  20260001  王娟杰  125.0  103  131  100   61  -61  A  D    C  459.0
1  20260002  宋强玲    NaN   90   88   40    0   97  B  C    A    NaN
2  20260003  朱芳伟   76.0   59  150   61   70   25  C  A    C  441.0
3  20260004  赵军鑫   87.0  141  118   49   37   63  B  A    D  495.0
4  20260005  黄玲勇  137.0   65  115    9   28   74  D  C  NaN  428.0
5  20260006  高娟伟  116.0  139   73   21   91   52  B  B    C  492.0
6  20260007  杨勇明  119.0   95   84   86   99   96  C  A    B  579.0
7  20260008  黄明强   55.0  146  102   56  100   41  C  D    B  500.0
8  20260009  刘秀秀  121.0   85  121  100   67  100  C  B    A  594.0
9  20260010  许芳丽   58.0  144  140   69   52   23  C  B    A  486.0
          学号   姓名     语文   数学   英语   物理   化学   生物 体育 美术   音乐    总成绩
0   20260001  王娟杰  125.0  103  131  100   61  -61  A  D    C  459.0
1   20260002  宋强玲    NaN   90   88   40    0   97  B  C    A    NaN
2   20260003  朱芳伟   76.0   59  150   61   70   25  C  A    C  441.0
3   20260004  赵军鑫   87.0  141  118   49   37   63  B  A    D  495.0
4   20260005  黄玲勇  137.0   65  115    9   28   74  D  C  NaN  428.0
5   20260006  高娟伟  116.0  139   73   21   91   52  B  B    C  492.0
6   20260007  杨勇明  119.0   95   84   86   99   96  C  A    B  579.0
7   20260008  黄明强   55.0  146  102   56  100   41  C  D    B  500.0
8   20260009  刘秀秀  121.0   85  121  100   67  100  C  B    A  594.0
9   20260010  许芳丽   58.0  144  140   69   52   23  C  B    A  486.0
10  20260011  曹华娜   80.0   90  140   78   52   83  D  C    D  523.0

In [43]:
#数据过滤
#数字筛选
df[df['语文'] >= 150]
df[df['数学'].between(60,90)] #默认全闭
#文字筛选
df[df['体育'].isin(['A'])]
#逻辑关系
#和
df[(df['语文'] >= 150) & (df['数学'] >= 90)]
#或
df[(df['语文'] >= 150) | (df['数学'] >= 90)]
 #非
df[~(df['语文'] >= 150)]

           学号   姓名   语文   数学   英语   物理  化学   生物 体育 美术 音乐
0    20260001  王娟杰  125  103  131  100  61   61  A  D  C
1    20260002  宋强玲   88   90   88   40   0   97  B  C  A
3    20260004  赵军鑫   87  141  118   49  37   63  B  A  D
5    20260006  高娟伟  116  139   73   21  91   52  B  B  C
6    20260007  杨勇明  119   95   84   86  99   96  C  A  B
..        ...  ...  ...  ...  ...  ...  ..  ... .. .. ..
993  20260994  周杰强   91  136  133   60  58  100  D  B  C
994  20260995  高玲艳   38  120   95   77  86  100  B  B  D
995  20260996  孙伟勇  123  150   80   74  26   64  B  C  D
996  20260997  邓鑫艳   62   93  139   79  85   79  C  C  A
998  20260999  张艳强  112  119  111  100  72   24  C  C  B

[715 rows x 11 columns]

In [7]:
#数据清洗
#处理缺失值
#查看缺失值
df.isnull()
#删除缺失值
df.dropna()#删除行
df.dropna(axis=1)#删除列
#填充缺失值
df.fillna(0)#用0填充
df.ffill()#用前一个值填充
df.bfill()#用后一个值填充
df.fillna(value={'语文': 0, '数学': 0, '英语': 0, '物理': 0, '化学': 0, '生物': 0})#用指定值填充

           学号   姓名     语文   数学   英语   物理  化学  生物 体育 美术   音乐    总成绩
0    20260001  王娟杰  125.0  103  131  100  61 -61  A  D    C  459.0
1    20260002  宋强玲    0.0   90   88   40   0  97  B  C    A    NaN
2    20260003  朱芳伟   76.0   59  150   61  70  25  C  A    C  441.0
3    20260004  赵军鑫   87.0  141  118   49  37  63  B  A    D  495.0
4    20260005  黄玲勇  137.0   65  115    9  28  74  D  C  NaN  428.0
..        ...  ...    ...  ...  ...  ...  ..  .. .. ..  ...    ...
995  20260996  孙伟勇  123.0  150   80   74  26  64  B  C    D  517.0
996  20260997  邓鑫艳   62.0   93  139   79  85  79  C  C    A  537.0
997  20260998  王静敏   67.0   52  135   69  54  36  B  C    D  413.0
998  20260999  张艳强  112.0  119  111  100  72  24  C  C    B  538.0
999  20261000  马艳艳   58.0   60  106   85  92  93  B  C    D  494.0

[1000 rows x 12 columns]

In [8]:
#重复值处理
#查看重复值
df.duplicated()#判断所有列数据全都一样
df.duplicated(subset=['姓名'])#判断指定列数据一样
#删除重复值
df.drop_duplicates(subset = ['姓名'], keep='first')#删除重复值，只保留第一个
df.drop_duplicates(subset = ['姓名'], keep='last')#删除重复值，只保留最后一个
df.drop_duplicates(subset = ['姓名'], keep=False)#删除重复值，不留任何

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
#处理异常值
#查看异常值
df[df['语文'] > 150]#查看异常值
#删除异常值
df.drop(df[df['语文'] > 150].index)
#修复异常值
df['语文'].replace(150, 100)#修复异常值

In [ ]:
#数据格式处理
#df['日期'] = df['日期'].str.replace('/','-')